### ISSUE TITLE
Impossible to make 32 bit baseimage-docker?

### ISSUE THREAD

**Issue by danryu** [phusion/baseimage-docker#349] opened 2016-11-16 09:06 UTC
Hi - cool project by the way, have been enjoying it ....

I'm trying to see if I can make a minimal 32 bit base image to host an application which doesn't have to be 64bit, and which could benefit in terms of size from just being 32 bit (there's a Wine installation involved, which is a good deal simpler when just 32 bit).

So I tried seeing if I could make my own 32 bit image by just changing the first line of the Dockerfile to
`FROM 32bit/ubuntu:16.04`
and then building locally.

But after a while the build died like this:
```
Setting up python3-six (1.10.0-3) ...
Setting up python3-debian (0.1.27ubuntu2) ...
Setting up gdebi-core (0.9.5.7ubuntu1) ...
+ apt-get build-dep -y --no-install-recommends pam
Reading package lists...
E: You must put some 'source' URIs in your sources.list
The command '/bin/sh -c /bd_build/prepare.sh && 	/bd_build/system_services.sh && 	/bd_build/utilities.sh && 	/bd_build/fix_pam_bug.sh && 	/bd_build/cleanup.sh' returned a non-zero code: 100
```

Could you let me know if this will be possible at all, or I'm just wasting my time?

Any feedback warmly appreciated.
Cheers!

**Comment by dquintela** [comment] 2016-11-16 10:34
You should use images https://hub.docker.com/r/i386/
There are built for i386 the same way as original ones..

**Comment by dan-garton-neoworks** [comment] 2016-11-16 11:21
Thanks for the response.
I assume you meant to use the image https://hub.docker.com/r/i386/ubuntu/ and thus make this the first line in Dockerfile:
`FROM i386/ubuntu:16.04`

So I tried this, and unfortunately the subsequent "docker build ." then results in the following build failure:

```
E: Unable to locate package libtsan0
The command '/bin/sh -c /bd_build/prepare.sh && 	/bd_build/system_services.sh && 	/bd_build/utilities.sh && 	/bd_build/fix_pam_bug.sh && 	/bd_build/cleanup.sh' returned a non-zero code: 100
```

Am I trying something which is fundamentally unsupported, or am I just doing this wrong?

**Comment by danryu** [comment] 2016-11-16 11:22
Thanks for the response.
I assume you meant to use the image https://hub.docker.com/r/i386/ubuntu and thus make this the first line in Dockerfile:
`FROM i386/ubuntu:16.04`

So I tried this, and unfortunately the subsequent "docker build ." then results in the following build failure:

```
E: Unable to locate package libtsan0
The command '/bin/sh -c /bd_build/prepare.sh &&     /bd_build/system_services.sh &&     /bd_build/utilities.sh &&   /bd_build/fix_pam_bug.sh &&     /bd_build/cleanup.sh' returned a non-zero code: 100
```

Am I trying something which is fundamentally unsupported, or am I just doing this wrong?

**Comment by dquintela** [comment] 2016-11-16 11:37
Well I have been watching this project for the same reason: i386 support. But haven't work on this - I am not affiliated whatsoever.

A quick check at http://packages.ubuntu.com/xenial/libs/libtsan0
Says it's only available for amd64 - that may be the reason for the build failure. However I don't know the package or why is it used in this context - sorry.

**Comment by danryu** [comment] 2016-11-16 21:55
FWIW, I tried rolling back to Trusty like so
`FROM i386/ubuntu:14.04`
but still a whole bunch of broken dependencies. Very much have the feeling that i386 isn't just a simple switch:
```
  Selecting previously unselected package libpam-doc.
(Reading database ... 20125 files and directories currently installed.)
Preparing to unpack libpam-doc_1.1.8-1ubuntu2.2_all.deb ...
Unpacking libpam-doc (1.1.8-1ubuntu2.2) ...
Setting up libpam-doc (1.1.8-1ubuntu2.2) ...
Building data structures... Done
+ rm -rf libpam-cracklib_1.1.8-1ubuntu2.2_i386.deb libpam-doc_1.1.8-1ubuntu2.2_all.deb libpam-modules-bin_1.1.8-1ubuntu2.2_i386.deb libpam-modules_1.1.8-1ubuntu2.2_i386.deb libpam-runtime_1.1.8-1ubuntu2.2_all.deb libpam0g-dev_1.1.8-1ubuntu2.2_i386.deb libpam0g_1.1.8-1ubuntu2.2_i386.deb pam_1.1.8-1ubuntu2.2.diff.gz pam_1.1.8.orig.tar.gz pam_1.1.8-1ubuntu2.2.dsc pam_1.1.8-1ubuntu2.2_i386.changes pam-1.1.8
+ apt-get remove -y gdebi-core autoconf automake autopoint autotools-dev binutils bsdmainutils build-essential bzip2 cpp cpp-5 debhelper dh-autoreconf dh-strip-nondeterminism diffstat docbook-xml docbook-xsl dpkg-dev flex g++ g++-5 gcc gcc-5 gettext gettext-base groff-base intltool-debian libarchive-zip-perl libasan2 libasprintf0v5 libatomic1 libaudit-dev libc-dev-bin libc6-dev libcc1-0 libcilkrts5 libcrack2 libcrack2-dev libcroco3 libdb-dev libdb5.3-dev libdpkg-perl libfile-stripnondeterminism-perl libfl-dev libgc1c2 libgcc-5-dev libgdbm3 libgomp1 libgpm2 libicu55 libisl15 libitm1 liblsan0 libmpc3 libmpfr4 libmpx0 libpcre16-3 libpcre3-dev libpcre32-3 libpcrecpp0v5 libperl5.22 libpipeline1 libquadmath0 libselinux1-dev libsepol1-dev libsigsegv2 libstdc++-5-dev libtimedate-perl libtool libtsan0 libubsan0 libunistring0 libxml2 libxml2-utils libxslt1.1 linux-libc-dev m4 make man-db patch perl perl-modules-5.22 pkg-config po-debconf quilt sgml-base sgml-data w3m xml-core xsltproc xz-utils
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package cpp-5
E: Unable to locate package dh-strip-nondeterminism
E: Unable to locate package g++-5
E: Couldn't find any package by regex 'g++-5'
E: Unable to locate package gcc-5
E: Unable to locate package libasan2
E: Unable to locate package libasprintf0v5
E: Unable to locate package libcc1-0
E: Unable to locate package libcilkrts5
E: Unable to locate package libfile-stripnondeterminism-perl
E: Unable to locate package libgcc-5-dev
E: Unable to locate package libicu55
E: Unable to locate package libisl15
E: Unable to locate package liblsan0
E: Unable to locate package libmpx0
E: Unable to locate package libpcre16-3
E: Unable to locate package libpcre32-3
E: Unable to locate package libpcrecpp0v5
E: Unable to locate package libperl5.22
E: Couldn't find any package by regex 'libperl5.22'
E: Unable to locate package libstdc++-5-dev
E: Couldn't find any package by regex 'libstdc++-5-dev'
E: Unable to locate package libtsan0
E: Unable to locate package libubsan0
E: Unable to locate package perl-modules-5.22
E: Couldn't find any package by regex 'perl-modules-5.22'
The command '/bin/sh -c /bd_build/prepare.sh && 	/bd_build/system_services.sh && 	/bd_build/utilities.sh && 	/bd_build/fix_pam_bug.sh && 	/bd_build/cleanup.sh' returned a non-zero code: 100
```

**Comment by dquintela** [comment] 2016-11-17 07:03
Btw, trusty's package is also for amd64 only.
http://packages.ubuntu.com/trusty/libtsan0

**Comment by dquintela** [comment] 2016-11-17 07:08
According with http://software.opensuse.org/package/libtsan0
If you change the gcc flag to exclude --sanitize=thread you maybe could compile without the need for libtsan0 package

**Comment by Theaxiom** [comment] 2017-03-19 08:44
@danryu Unfortunately, I do not have the time to begin to attempt to make this work for 32-bit. That being said, if you do manage to get it working on 32-bit, please, by all means submit your pull request! Thank you!

**Comment by kingdonb** [comment] 2017-03-20 18:44
I am interested in this issue and have experience dockerizing things on 32-bit/i686 platform.  I will take a look.

**Comment by Theaxiom** [comment] 2017-03-20 18:56
Thank you @kingdonb

**Comment by kingdonb** [comment] 2017-03-20 23:06
@danryu Can you clue me in on where the i686 docker-engine binaries for your distro are coming from?  I'm on debian and it looks like I'm going to have to build from source.  What version are you on?

Build from source is OK with me, I just want to make sure there isn't an obvious source of binary deb distro that I missed, with binaries locked at a particular version because of some platform issue I'm going to spend hours debugging without their help...

**Comment by dan-garton-neoworks** [comment] 2017-03-21 00:14
@kingdonb This is a few months ago, but from what I remember, I was working with stock Ubuntu 64bit 16.04, with Docker installed either from apt (maybe even the old 1.12) or from the Docker site at https://docs.docker.com/engine/installation/linux/ubuntu/#install-docker.
Either way the problem isn't in the Docker version used to execute "docker build", but in the differing dependencies in the i386 tree versus the standard 64-bit.
So re-creating the build problem should be pretty simple:
- vagrant init ubuntu/xenial64; vagrant ssh
- git clone https://github.com/phusion/baseimage-docker
- replace Dockerfile first line with "FROM i386/ubuntu:16.04"
- docker build .

I just tried it now and it looks like the command xsltproc is failing during a pam module build:

> /usr/bin/xsltproc --path . --xinclude --stringparam generate.toc "none" --nonet http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl README.xml | /usr/bin/w3m -T text/html -dump > ./README
getcontext failed: Use another register retrieval method?
/bin/bash: line 1: 27932 Broken pipe             /usr/bin/xsltproc --path . --xinclude --stringparam generate.toc "none" --nonet http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl README.xml
     27933 Aborted                 (core dumped) | /usr/bin/w3m -T text/html -dump > ./README
make[4]: *** [README] Error 134
../../Make.xml.rules:6: recipe for target 'README' failed
make[4]: Leaving directory '/tmp/pam-1.1.8/modules/pam_access'
Makefile:431: recipe for target 'all-recursive' failed
make[3]: Leaving directory '/tmp/pam-1.1.8/modules'
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
Makefile:479: recipe for target 'all-recursive' failed
make[2]: Leaving directory '/tmp/pam-1.1.8'
Makefile:411: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/tmp/pam-1.1.8'
dh_auto_build: make -j1 returned exit code 2
debian/rules:21: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
Build command 'cd pam-1.1.8 && dpkg-buildpackage -b -uc' failed.
Fetched 2094 kB in 1s (1591 kB/s)
E: Sub-process dpkg-source returned an error code (1)
The command '/bin/sh -c /bd_build/prepare.sh && 	/bd_build/system_services.sh && 	/bd_build/utilities.sh && 	/bd_build/fix_pam_bug.sh && 	/bd_build/cleanup.sh' returned a non-zero code: 100

**Comment by danryu** [comment] 2017-03-21 00:16
@kingdonb This is a few months ago, but from what I remember, I was working with stock Ubuntu 64bit 16.04, with Docker installed either from apt (maybe even the old 1.12) or from the Docker site at https://docs.docker.com/engine/installation/linux/ubuntu/#install-docker.
Either way the problem isn't in the Docker version used to execute "docker build", but in the differing dependencies in the i386 tree versus the standard 64-bit.
So re-creating the build problem should be pretty simple:

- vagrant init ubuntu/xenial64; vagrant ssh
- git clone https://github.com/phusion/baseimage-docker
- replace Dockerfile first line with "FROM i386/ubuntu:16.04"
- docker build .

I just tried it now and it looks like the command xsltproc is failing during a pam module build:

> /usr/bin/xsltproc --path . --xinclude --stringparam generate.toc "none" --nonet http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl README.xml | /usr/bin/w3m -T text/html -dump > ./README
> getcontext failed: Use another register retrieval method?
> /bin/bash: line 1: 27932 Broken pipe /usr/bin/xsltproc --path . --xinclude --stringparam generate.toc "none" --nonet http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl README.xml
> 27933 Aborted (core dumped) | /usr/bin/w3m -T text/html -dump > ./README
> make[4]: *** [README] Error 134
> ../../Make.xml.rules:6: recipe for target 'README' failed
> make[4]: Leaving directory '/tmp/pam-1.1.8/modules/pam_access'
> Makefile:431: recipe for target 'all-recursive' failed
> make[3]: Leaving directory '/tmp/pam-1.1.8/modules'
> make[3]: *** [all-recursive] Error 1
> make[2]: *** [all-recursive] Error 1
> Makefile:479: recipe for target 'all-recursive' failed
> make[2]: Leaving directory '/tmp/pam-1.1.8'
> Makefile:411: recipe for target 'all' failed
> make[1]: *** [all] Error 2
> make[1]: Leaving directory '/tmp/pam-1.1.8'
> dh_auto_build: make -j1 returned exit code 2
> debian/rules:21: recipe for target 'build' failed
> make: *** [build] Error 2
> dpkg-buildpackage: error: debian/rules build gave error exit status 2
> Build command 'cd pam-1.1.8 && dpkg-buildpackage -b -uc' failed.
> Fetched 2094 kB in 1s (1591 kB/s)
> E: Sub-process dpkg-source returned an error code (1)
> The command '/bin/sh -c /bd_build/prepare.sh && /bd_build/system_services.sh && /bd_build/utilities.sh && /bd_build/fix_pam_bug.sh && /bd_build/cleanup.sh' returned a non-zero code: 100

**Comment by kingdonb** [comment] 2017-03-21 00:47
It looks to me like docker/docker has gone out of their way to "not support" i386/i686 architecture.  There is Dockerfile.armhf in the docker/docker tree!  But no Dockerfile.i386 or Dockerfile.x86, etc.

Accordingly I had no idea that docker.io was just supported on any arbitrary release of ubuntu i386.  That's very interesting.

Baseimage can target Docker on Ubuntu i386 as host!  That would make sense given Ubuntu image inside of baseimage. It will be harder to support in the next release if binary goes away.  But in Ubuntu there is no sign of it (newer docker.io packages in yakkety than in xenial).  So, Debian politics problem I guess?.

It seems like you have no choice but to compile from source on i686 debian/sid.  Compiling docker from source requires a docker engine binary first.  I'm sure that's exactly how it started.

I have thus not been able to build docker on debian/sid unstable or latest, in about an hour now.  Sid actually has no docker.io or docker-engine package in tree for that arch.  Reading docker/docker/issues/3768 had me start to get worried.  Good thing this is Ubuntu baseimage-docker and not Debian-baseimage-docker.

I'll go get an Ubuntu host system and try again.

**Comment by kingdonb** [comment] 2017-03-21 01:30
Yes, I see

So it fails running /bd_build/fix_pam_bug.sh

Kind of looks like issue described in ivmai/bdwgc/issues/133

It does not seem to respond at all to setting NO_GETCONTEXT in the env as that thread suggested

w3m is the program dumping core and http://git.net/ml/debian-bugs-dist/2011-05/msg00243.html looks like a dead-end about that...

Do we know if fix_pam_bug.sh pam bug still needs to be fixed in 16.04 LTS?  The fix script went in quite some time ago, don't even know if it's still relevant, although it seems likely we will hit this issue again and might be worth working through.

**Comment by kingdonb** [comment] 2017-03-21 01:37
I think it's actually libgc that had to be built with NO_GETCONTEXT, and it looks like that fix to ivmai/bdwgc#133 was merged fairly recently, at least on geologic time scale of LTS releases...

Looks like libgc actually cut its last release on August 8, and this fix got merged August 12, but no releases since!  Guess I could try and contribute a /bd_build/fix_libgc.sh and/or fix_w3m.sh.

**Comment by kingdonb** [comment] 2017-03-21 02:39
Good news, I can build a libgc that doesn't fail its own self tests by rebuilding it, setting NO_GETCONTEXT

```
============================================================================
Testsuite summary for gc 7.4.2
============================================================================
# TOTAL: 15
# PASS:  15
```

That self-test on libgc was failing without the #define added and it passes now, wahoo.  More good news after that, just adding a libgc dynamic lib with this fix included makes w3m not crash whilst generating pam modules' documentation in fix_pam_bug.sh.

So, it can be fixed!  It's a workaround though.  I'll amend PR with any suggestions, tomorrow.  Not sure what the best way to build a package from slightly modified source is, but it seems the easiest way is with `dpkg_buildpackage -b`.

Also not entirely sure I haven't removed something important.  Marking as WIP.

**Comment by Theaxiom** [comment] 2017-03-21 03:38
@kingdonb I merged your changes into an i386 branch. Thanks!

**Closed** 2017-04-23 07:26 UTC
Labels: discussion, wontfix
