### ISSUE TITLE
runit daemon did not shut down in time

### ISSUE THREAD

**Issue by j0hnsmith** [phusion/baseimage-docker#151] opened 2014-10-13 09:37 UTC
From https://github.com/phusion/passenger-docker/issues/51

If I kill a container while it's still starting, it completely hangs:

    *** Running bash -l...
    ^C*** Shutting down bash (PID 10)...

    *** Shutting down runit daemon (PID 9)...
    ok: run: /etc/service/nginx-log-forwarder: (pid 27) 1s
    *** runit daemon (PID 9) did not shut down in time. Forcing it to exit.
    <stuck forever>

The only way I've been able to recover is by `kill -9 <pid>`.

**Comment by glerchundi** [comment] 2015-02-04 21:25
same here, sometimes it gets stuck trying to do a graceful stop.

any plan on this?

**Comment by Toilal** [comment] 2015-02-28 09:38
I have the same issue, with multiple Dockerfile on 3 distinct hosts.

**Comment by Toilal** [comment] 2015-03-02 08:35
In my case, it seems to only occur when runit try to start services that fails to run. runit retry every second to start service, and maybe there's a race condition when shutting down the container in this state ...

**Comment by qzio** [comment] 2015-03-12 15:57
I have the same issue.

When this happen, I can enter the container and confirm that nothing besides my_init and some runsv processes are running.

If I do `sv status` on all my services they all displays  as "down"

**Comment by SAPikachu** [comment] 2015-04-14 07:04
I also encountered this issue. Looks like it is because the runit daemon exits before `waitpid_reap_other_children()` catches that.

As a workaround, I changed this line inside `waitpid_reap_other_children` (around line 121):
```
			this_pid, status = os.waitpid(-1, 0)
```
to:
```
			this_pid, status = os.waitpid(pid, os.WNOHANG)
			if this_pid == 0:
				this_pid, status = os.waitpid(-1, 0)
```

With this, seems the issue goes away. Not quite sure how to properly fix this though.

**Comment by lingz** [comment] 2015-05-20 08:23
Can confirm that I have the same issue on my repo here: https://github.com/lingz/docker-wordpress-hhvm-php-fpm-fallback

but that @SAPikachu proposed change fixed it for me as well.

**Comment by robbles** [comment] 2015-06-15 15:37
Is there a fix for this bug planned? Looks like @SAPikachu's fix might work?

I just ran into it and had to skip using baseimage-docker for now as a result. Having containers that could hang in production when they're restarted worries me, and even if there's a workaround with switching drivers, it's pretty disruptive in development as well.

**Comment by FooBarWidget** [comment] 2015-07-15 15:03
I've finally had some time to look at the issue list again, so I'm investigating this now.

**Comment by FooBarWidget** [comment] 2015-07-15 15:31
I tried reproducing this issue, but has no luck doing that at all. I'm not even using the LXC driver. Even when I comment out some code (e.g. the `kill` call) to try to simulate the problem, I still couldn't reproduce it. Having said that, @SAPikachu's fix looks sane enough, so I'll incorporate it.

**Closed** 2015-07-15 15:36 UTC
