### ISSUE TITLE
logrotate requires a syslog user

### ISSUE THREAD

**Issue by jzelinskie** [phusion/baseimage-docker#338] opened 2016-09-08 00:57 UTC
L7 of `/etc/logrotate.conf` configures syslog to be the user to rotate logs. There is no syslog user so this is failing.

I'm willing to open a PR to fix this if we can decide the best way forward. Changing the user to root works, but is probably not ideal.

**Comment by jzelinskie** [comment] 2016-09-08 00:59
cc @zhouhaibing089

**Comment by zhouhaibing089** [comment] 2016-09-12 02:06
The `/etc/logrotate.conf` is produced by base image `ubuntu:16.04`:

```console
$ docker run -it ubuntu:16.04 bash
$ apt-get update && apt-get install logrotate
$ cat /etc/logrotate.conf
# see "man logrotate" for details
# rotate log files weekly
weekly

# use the syslog group by default, since this is the owning group
# of /var/log/syslog.
su root syslog

# keep 4 weeks worth of backlogs
rotate 4

# create new (empty) log files after rotating old ones
create

# uncomment this if you want your log files compressed
#compress

# packages drop log rotation information into this directory
include /etc/logrotate.d

# no packages own wtmp, or btmp -- we'll rotate them here
/var/log/wtmp {
    missingok
    monthly
    create 0664 root utmp
    rotate 1
}

/var/log/btmp {
    missingok
    monthly
    create 0660 root utmp
    rotate 1
}

# system-specific logs may be configured here
```

**Comment by zhouhaibing089** [comment] 2016-09-12 02:09
Few more:

```console
root@bd704052944d:/# apt-get install syslog-ng-core
root@bd704052944d:/# id syslog
id: 'syslog': no such user
```

**Comment by zhouhaibing089** [comment] 2016-09-12 02:12
While it is fine on ubuntu:14.04, refer this commit for base image change: https://github.com/phusion/baseimage-docker/commit/e436d1c4af16a5e9590ae4e48e5105f1db787e7f

```console
$ docker run -it ubuntu:14.04 bash
root@aa543e8da7e3:/# id syslog
uid=101(syslog) gid=104(syslog) groups=104(syslog),4(adm)
```

**Comment by zhouhaibing089** [comment] 2016-09-12 02:23
As far as I know, ubuntu:16.04 already migrated to use systemd, so I guess that's the reason why no syslog user/group any more..

**Comment by sam0737** [comment] 2016-11-09 06:40
systemd won't work for sure because the whole init stack is replaced. just like upstart were replaced in the previous version.
syslog group is present on a vanilla 16.04 system though. Not sure why it wasn't created in phusion/base_image

**Comment by zas** [comment] 2016-11-22 10:19
In the meantime i'm using the following in my `Dockerfile`
```
RUN sed -i 's/^su root syslog/su root adm/' /etc/logrotate.conf
```

**Comment by hyperknot** [comment] 2016-11-24 14:28
I'm trying to understand this bug and fix it. 
Two questions:
1. But even in the unfixed form, it seems to work fine. If I run 
`logrotate -d /etc/logrotate.d/syslog-ng` it does the rotations for me (can test with `--force`). The new files get `root adm` by default.

2. I don't understand how does logrotate work at all. It should be a service, which is run by runit, yet in baseimage it is not a service. Why would it run?

**Comment by neris** [comment] 2016-11-24 14:30
> I don't understand how does logrotate work at all. It should be a service, which is run by runit, yet in baseimage it is not a service. Why would it run?

It's being executed by `cron`, which is present in the baseimage as a runit service.

**Comment by hyperknot** [comment] 2016-11-24 15:05
@neris probably it's via `/etc/crontab` -> `run-parts /etc/cron.daily`, so I see it.

Now the actual problem, can you tell me how can I reproduce it? As I said even with `root syslog` it seems to work for me, although I haven't tried it via run-parts.

**Comment by hyperknot** [comment] 2016-11-24 15:13
OK, I was able to reproduce it via `run-parts -v /etc/cron.daily/` and I can confirm that 
```
sed -i 's/^su root syslog/su root adm/' /etc/logrotate.conf
```

Does indeed fix it.

**Comment by hyperknot** [comment] 2016-11-24 16:05
I started making an updated fork of this project, containing Ubuntu 16.04 fixes, including this one. Have a look here:
https://github.com/hyperknot/baseimage16

**Comment by hyperknot** [comment] 2016-11-26 14:04
Created an Ubuntu bug, should be also fixed upstream:
https://bugs.launchpad.net/ubuntu/+source/logrotate/+bug/1644996

**Comment by Theaxiom** [comment] 2017-03-19 08:08
Fixed by https://github.com/phusion/baseimage-docker/commit/fdda2d42bfc3eb62e6a3930e8e0ecdca8c06ed55

**Closed by Theaxiom** 2017-03-19 08:08 UTC
