### ISSUE TITLE
Cron jobs return "System error"

### ISSUE THREAD

**Issue by runn1ng** [phusion/baseimage-docker#144] opened 2014-09-25 03:12 UTC
I am trying to run cronjobs on my docker image; they never run, and all that happens is that "System error" is written on the output.

It doesn't matter what the cronjob is, how often it is, and so on. There is zero other log output.

The same thing happened when I tried to run a "vanilla" ubuntu image and "cron -f", so I can't really tell where is the actual error.

The same thing happened with 0.9.13 (where the "System error" is written on STDOUT) and with 0.9.10 (where the "System error" is written in /var/log).

The "outside" system is Trusty on Linode. I have zero clue where is the error.

**Comment by FooBarWidget** [comment] 2015-01-19 16:44
Marking this for 0.9.16. Sorry for the delay.

**Comment by FooBarWidget** [comment] 2015-01-19 16:53
I think this is a duplicate of #115. I'll fix both at the same time.

**Closed by FooBarWidget** 2015-01-19 16:53 UTC
Labels: bug

**Comment by Erfa** [comment] 2015-05-06 12:17
I had the exact same problem, just a "System error" in STDOUT from cron. In my case, the problem was that I used the --net="host" parameter when running the application. When I removed that, it worked fine.

**Comment by vimondketil** [comment] 2015-05-20 19:19
I can confirm the same behaviour as @Erfa – i get a "CRON[531]: System error" when running in --net="host" mode. Is this to be expected, or is it fixable?

**Comment by banjoey** [comment] 2015-11-02 14:10
+1 for --net="host" exposing the problem. Apparently affects debian base images as well: https://github.com/docker-library/official-images/issues/744

Has anyone found a workaround?

**Comment by ezrast** [comment] 2015-11-05 03:48
@banjoey There's some discussion of this issue at https://github.com/docker/docker/issues/5899 - the suggested workaround is adding "--pid=host", which works for me. Keep in mind that this will expose the host's process information to the container.
