### ISSUE TITLE
Runit daemon hangs on early shutdown

### ISSUE THREAD

**Issue by jperville** [phusion/baseimage-docker#274] opened 2015-12-28 10:12 UTC
# Synopsis

When an image based on baseimage is restarted (or gracefully stopped) very early after booting, the container will hang forever (or until the grace delay is up, then the container is ungracefully shutdown, which I want to avoid).

This may be related to #151, which was fixed in version 0.9.18, however I can still reproduce as of the current version.

# How to reproduce

```sh
$ docker run -d --name=xxx phusion/baseimage:0.9.18 && time docker restart --time=120 xxx
# the bug triggers more often with heavier image, eg. `docker run -d --name=xxx phusion/passenger-full:0.9.18 && time docker restart --time=120 xxx`.
340f9ce59ad1b92717b2e1bc1f23ed7f5d8169df9d2d575ad5f359a4cbe99865
xxx
docker restart --time=120 xxx  0.03s user 0.00s system 0% cpu 2:00.56 total
```

What is expected: the container should restart in very little time (1 second or so) without waiting for the grace delay.
What happens (sometimes, and almost always if using heavier image such as phusion/passenger-full:0.9.18): the container hangs until the grace delay is up (120 seconds).

Here is the docker logs for the stuck container:

```
$ docker logs -f xxx
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 8
Dec 28 09:58:25 340f9ce59ad1 syslog-ng[15]: syslog-ng starting up; version='3.5.3'
```

I believe that in my case the graceful shutdown happens when `/sbin/my_init` is still starting up, before it has initialized its SIGTERM handler.

**Comment by jperville** [comment] 2015-12-28 10:14
As a workaround, I `sleep 1` after creating the container, to give it time to boot up enough to respond to signals but this is far from ideal.

**Comment by skyscooby** [comment] 2016-02-15 03:41
You would have to code the my_init in native code or switch to https://github.com/krallin/tini.. there is no way around waiting a second for the python3 based my_init to be interpreted and executed.

**Comment by FooBarWidget** [comment] 2016-07-08 16:58
Maybe this is a duplicate of #315, which has now been fixed. I'm closing this bug until someone else reports this again.

**Closed by FooBarWidget** 2016-07-08 16:58 UTC
Labels: bug
